dist: trusty
sudo: false

language: node_js

node_js:
  - "11"
  - "10"
  - "8"
  - "6"
  - "4"

os:
  - linux
  - osx

install:
  - g++ --version
  - node --version
  - npm --version
  - npm install

script:
  - npm test
