sudo: false

language: cpp

node_js:
    - "9"
    - "8"
    - "7"
    - "6"
    - "5"
    - "4"

os:
  - linux
  - osx

install:
  - $CXX --version
  - node --version
  - npm --version
  - npm install

script:
  - npm test
