dist: trusty

language: node_js

node_js:
  - "15"
  - "14"
  - "12"
  - "10"
  - "8"
  - "6"

os:
  - linux
  - osx

install:
  - g++ --version
  - node --version
  - npm --version
  - npm install

script:
  - npm test
