# http://www.appveyor.com/docs/appveyor-yml

environment:
  # Test against these versions of Node.js
  matrix:
    # node.js
    - nodejs_version: "12"
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"

# Build on both platforms
platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Select node version $env:nodejs_version
  - ps: |
        try {
          Install-Product node $env:nodejs_version $env:platform
        } catch {
          echo "Unable to install node $env:nodejs_version, trying update..."
          Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
        }
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Install modules
  - npm install

# Post-install test scripts.
test_script:
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
