# http://www.appveyor.com/docs/appveyor-yml

environment:
  # Visual Studio Version
  MSVS_VERSION: 2013
  # Test against these versions of Node.js and io.js
  matrix:
    # node.js
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    # io.js
    - nodejs_version: "1.0"

# Build on both platforms
platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest version of $env:nodejs_version
  - ps: if($env:nodejs_version -eq "0.8") {Install-Product node $env:nodejs_version} $env:platform
  - ps: if($env:nodejs_version -ne "0.8") {Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)} $env:platform
  # Install latest NPM only for node.js versions until built in node-gyp adds io.js support
  # Update is required for node.js 0.8 because built in npm(node-gyp) does not know VS2013
  - IF NOT %nodejs_version% == 1.0 npm -g install npm
  - IF NOT %nodejs_version% == 1.0 set PATH=%APPDATA%\npm;%PATH%
  # Install modules
  - npm install --msvs_version=%MSVS_VERSION%

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
