# http://www.appveyor.com/docs/appveyor-yml

environment:
  # Test against these versions of Node.js and io.js
  matrix:
    # node.js
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"
    # io.js
    - nodejs_version: "3"
    # node.js
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"
    - nodejs_version: "0.8"

# Build on both platforms
platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest version of $env:nodejs_version
  - ps: >-
      If($env:nodejs_version -eq "0.8") {
        Install-Product node $env:nodejs_version $env:platform
      } Else {
        Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
      }
  # Install latest NPM@2 for node.js 0.8, 0.10 and 0.12 because built in npm(node-gyp) does not know VS2015
  - ps: >-
      If($env:nodejs_version.Length -ne 1) {
        npm -g install npm@2 2>&1>$null
        $env:PATH = $env:APPDATA + "\npm;" + $env:PATH
      }
  # Output useful info for debugging.
  - ps: node --version
  - ps: npm --version
  # Install modules
  - ps: npm install

# Post-install test scripts.
test_script:
  # run tests
  - ps: npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
